### ISSUE TITLE
"[esri.core.Accessor] Accessor#set Invalid property value" and "[esri.views.2d.layers.FeatureLayerView2D] TypeError: Cannot read property 'constructor' of undefined"

### ISSUE THREAD

**Issue by slead** [Esri/jsapi-resources#225]
Another issue with the webpack demo at https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo - both sample layers are returning the error message:

> Logger.js:25 [esri.core.Accessor] Accessor#set Invalid property value, value needs to be one of 'esri.symbols.SimpleFillSymbol', 'esri.symbols.PictureFillSymbol', 'esri.symbols.PictureMarkerSymbol', 'esri.symbols.SimpleLineSymbol', 'esri.symbols.SimpleMarkerSymbol', 'esri.symbols.TextSymbol', 'unknown', 'unknown', 'unknown', 'unknown', 'unknown', 'esri.symbols.CIMSymbol', or a plain object that can autocast (having .type = 'simple-fill', 'picture-fill', 'picture-marker', 'simple-line', 'simple-marker', 'text', 'line-3d', 'mesh-3d', 'point-3d', 'polygon-3d', 'web-style', 'cim')

![Screen Shot 2020-10-21 at 10 17 05 am](https://user-images.githubusercontent.com/133596/96654281-a33a8980-1386-11eb-959a-0d96242a40de.png)

In the case of this demo the layers seem to draw OK despite the error message, but in my example I'm seeing this additional error message and the feature layers aren't drawing at all.

> [esri.views.2d.layers.FeatureLayerView2D] TypeError: Cannot read property 'constructor' of undefined
    at Object.s [as getOwnClassMetadata] (metadata.js:25)

```
let layer3 = new FeatureLayer({
  url: "https://services7.arcgis.com/nMBRP09Dx4VqvXeZ/arcgis/rest/services/Indigenous_Locations/FeatureServer/0/",
  renderer: {
    type: "simple",
    symbol: {
      type: "simple-marker",
      style: "circle",
      color: "#6e6e6e",
      size: "9px",
      outline: {
        color: [ 255, 255, 255 ],
        width: 1
      }
    }
  }
})
map.add(layer3)
```

 Any suggestions? thanks

**Comment by COV-GIS** [comment]
At 4.17 including `'3d': false,` as a plugin feature breaks 2D feature layer symbols.

https://github.com/Esri/jsapi-resources/blob/master/4.x/webpack/demo/webpack.config.js#L78

**Comment by odoe** [comment]
Don't set `3d: false` for now in the plugin. There are some cross dependencies for 2d and 3d, it's when it excludes all 3d here.
https://github.com/Esri/arcgis-webpack-plugin/blob/master/lib/features.js#L63

You can add your own excludes of stuff like SceneView if you want, but full 3d exclusion won't work right now. Should be fixed in next release of the plugin.

**Comment by slead** [comment]
@odoe thanks for the info. However, I'm still seeing the errors despite the changes that you made to the repo. Are you also seeing them?

Any further suggestions? Thanks

**Comment by odoe** [comment]
No, I'm not getting that error, even with the `layer3` snippet you provided above. I get a font error, but only because a font is used not available on Online, but it uses a fallback.

Did you remove the `"3d": false` from the webpack config?

**Comment by slead** [comment]
If you're not seeing the error I'll close this for now, as I'm actually using a different approach on my current project. Thanks for the fast responses
